indexer/indexer_monitors.tf, indexer/providers.tf, indexer/variables.tf, indexer_dashboards/variables.tf, modules/indexer_dashboards/versions.tf, modules/indexer_monitors/monitors.tf, modules/indexer_monitors/variables.tf, modules/indexer_monitors/versions.tf
Before this PR is merged, I will add the monitoring_datadog_app_key, monitoring_slack_channel, monitoring_env_tag, and enable_monitoring to all environments
TODO:
- Add synthetics
=> [IND-376]: Setup Indexer monitors

modules/indexer_monitors/monitors.tf, modules/indexer_monitors/synthetic_monitors.tf
ecs_cluster_name is incorrect, because we use ecs_cluster_name as the cluster name for the full node, not the indexer
Also fixing the url for trades
=> Fix monitors

indexer/variables.tf, modules/indexer_monitors/locals.tf, modules/indexer_monitors/monitors.tf, modules/indexer_monitors/variables.tf
- Improve variable description for users
- Fix synthetic monitors. The monitor_suffix was a string literal so it work in the json but not in regular strings
=> Minor fixes to monitoring

modules/indexer_monitors/monitors.tf
alert if there hasn't been a fast sync snapshot uploaded in the last day
=> [IND-297] add monitor for fast sync snapshots

indexer/locals.tf, indexer/variables.tf
=> [IND-369] Add flag for compliance client selection.

modules/metric_ingestor/iam.tf
This prevents polluting the logs with error messages about the inability to get ContainerInstanceTags and TaskTags.
Example logs:
```
level=info time=2023-10-10T09:11:41Z msg="Processing credential request, credentialType=TaskApplication taskARN=arn:aws:ecs:ap-northeast-1:632121848170:task/testnet-metric-ingestor-cluster/7617a499a59c45e9a65025baca6330fe" module=credentials_handler.go
level=error time=2023-10-10T09:11:42Z msg="Task Metadata error: unable to get 'ContainerInstanceTags' for 'arn:aws:ecs:ap-northeast-1:632121848170:container-instance/testnet-metric-ingestor-cluster/0147ca125f864545baf008d32b60a49c': AccessDeniedException: User: arn:aws:sts::632121848170:assumed-role/testnet-metric-ingestor-EcsInstanceRole/i-083bcb4e16ce842a2 is not authorized to perform: …
```
=> Allow ListTagsForResource action for Metric Ingestor IAM role

indexer/indexer_monitors.tf, indexer/variables.tf, modules/indexer_monitors/monitors.tf, modules/indexer_monitors/precautionary_monitors.tf, modules/indexer_monitors/variables.tf
=> [IND-429]: Create precautionary monitors for tracking block processing speed

indexer/rds.tf
This was critical in narrowing down the query that was slow for the attached issue.
=> [CT-423] Enable nested statement statistics tracking.

indexer/rds.tf
RDS instances were automatically upgraded to 12.17.
=> Upgrade RDS minor version.

modules/datadog_agent/main.tf
=> [CT-666] make datadog agent non-essential

indexer/backup_full_node_ap_northeast_1.tf, indexer/route_table.tf, indexer/security_group.tf, indexer/terraform.tfvars, indexer/variables.tf, indexer/vpc.tf, modules/validator/ecs.tf, modules/validator/variables.tf
=> Add backup full node that writes on-chain messages to Kafka

modules/indexer_dashboards/comlink_dashboard.tf
Success rate dashboard isn't that meaningful. because of 404s on address controller, 429s on screen controller.
Add separate dash for ISE rate.
=> add ISE rate dashboard + fix existing success rate dash

modules/indexer_monitors/locals.tf, modules/indexer_monitors/monitors.tf
- Also add re-notification to the monitor on a 12 hour interval for no data alerts, mainly for environments where there is no paging
=> [DEC-2216] Add no data alert to fast sync snapshots monitor.

indexer/backup_full_node_ap_northeast_1.tf, indexer/full_node_ap_northeast_1.tf, indexer/variables.tf
Add full_node_root_block_device_size to easy reduce fullnode storage size
=> Add full_node_root_block_device_size to easy reduce fullnode storage size

indexer/msk.tf
Add simple condition to set storage of dev env to 500
=> Reduce msk storage of dev env to 500

indexer/variables.tf
add new variable: msk_storage_size to set storage of kafka
=> Add new variable: msk_storage_size to set storage of kafka

indexer/msk.tf
msk references configuration arn, so changing the configuration name does not require additional changes
=> Resolve msk configuration resource conflict for replacement

indexer/lambda.tf
Increases the default lambda timeout to 5 minutes
=> Increase lambda timeout to 5 mins

indexer/terraform.tfvars
Reverts dydxprotocol/v4-infrastructure#132
=> Revert "Remove apne-1a az"

indexer/load_balancer.tf
Use latest SSL security policy.
=> Update load balancer SSL policy.
