dydxprotocol/v4-infrastructure

indexer_dashboards/versions.tf
Use a different tag as dashboards config is different from indexer configs.
=> Use different workspaces for indexer dashboards.

modules/indexer_monitors/locals.tf, modules/indexer_monitors/synthetic_monitors.tf
Synthentic monitors are too flaky with just a single failure
=> Add retry for synthetic monitors

indexer/snapshot_full_node_ap_northeast_1.tf
fixes memory issue once snapshot is ~150 gb
=> increase ebs volume size for snapshot node from 250 gib to 500 gib

indexer/snapshot_full_node_ap_northeast_1.tf, indexer/variables.tf
Snapshot node uses `local_node` as its home directory. Previously this didn't matter because it had its own entrypoint, but now that we are using cosmovisor, `DAEMON_HOME` (which is set from `container_chain_home`) needs to be set correctly so cosmovisor can use it.
=> Control snapshot node's home directory separately

indexer/ecs.tf, modules/datadog_agent/output.tf
I was investigating Indexer latency issues in dev5. There was a big [increase](https://app.datadoghq.com/dashboard/tn3-bgn-9jr/v4-indexer?refresh_mode=paused&tpl_var_cluster_name%5B0%5D=dev5-indexer-apne1-cluster&tpl_var_cluster%5B0%5D=dev5-indexer-apne1-cluster&tpl_var_container_name%5B0%5D=%2A&tpl_var_ecs_cluster_name%5B0%5D=%2A&tpl_var_ecs_task_family%5B0%5D=%2A&tpl_var_Environment%5B0%5D=dev5&tpl_var_msk_cluster_name%5B0%5D=dev5-indexer-apne1-msk-cluster&tpl_var_project%5B0%5D=v4&tpl_var_region%5B0%5D=%2A&tpl_var_Service%5B0%5D=indexer&tpl_var_task_name%5B0%5D=%2A&from_ts=1696392552286&to_ts=1696444118000&live=false) in processing latency starting at 6 am today, causing us to lag behind the network. I verified this had nothing to do with valdiator <-> full node latency. Nothing …
=> [IND-405] set memory/cpu explicitly for Indexer service containers

modules/indexer_dashboards/ender_dashboard.tf, modules/indexer_dashboards/vulcan_dashboard.tf
rollup(sum) is for summing event counts over the time period. Changing the time window changes the value. It's not very useful.
We should be using avg.
=> change rollup(sum) to rollup(avg) in Indexer dashboards

indexer/ecs.tf, indexer/iam.tf, indexer/locals.tf
Note on the circular dependency that required the use of a new local variable for service names:
The secret roles I added need to loop over each service, and are used to create the ECS task role. The ECS task role is passed into the environment variables for `roundtable` in the service. If the secret roles depended on the `services` local, this causes a circular dependency.
This is good for the future as well, if we need to create any other resource per service, we should only loop over the names of the services if we don't need any of the details inside `local.services`, as there are more and more dependencies / data in `local.services`.
=> Add secrets access to task roles.

modules/indexer_monitors/monitors.tf
Remove best bid / best ask monitors as they don't account for order books with low volume.
Update metric for order book crossed monitor to default to zero when there is no data so that order books with low volume do not cause false positives.
Back-tested against order books with low volume and verified the metric was 0, and also back-tested against cases where the order book was crossed for an extended period of time and the metric was negative.
=> Update indexer monitors.

metric_ingestor/metric_ingestor.tf, metric_ingestor/variables.tf, modules/datadog_agent/variables.tf, modules/metric_ingestor/datadog.tf, modules/metric_ingestor/variables.tf
The goal of this PR is to allow passing DataDog module's DD_SITE parameter for Metric Ingestor.
`nullable = false` is used to ensure compatibility with existing Metric Ingestor configurations: when `null` parameter is passed into `datadog_agent` module, the `site` parameter will still keep its default value.
=> Parametrize DataDog API site in Metric Ingestor module

modules/indexer_monitors/monitors.tf
Without the consumer group if we create one-off consumers to read data from the topic, we will trigger the alerts.
=> Add consumer group to MSK max offset monitors.

modules/indexer_dashboards/ender_dashboard.tf
- Remove deprecated `max:dydxprotocol.tendermint_consensus_height`
- Changed ender processing block height from avg to max, because during auxo deployment, there are two instances of ender, so avg is inaccurate and it looks like ender is lagging while auxo is redeploying ender
=> Update Ender Block Processing dashboard

indexer/rds.tf
Disable auto minor version upgrades, instead these upgrades should be manually applied so that a status page / maintenance alert can be sent out ahead of time.
=> Disable RDS auto minor version upgrades.

modules/indexer_monitors/precautionary_monitors.tf
Increase params to the alert from:
- alerting when average replica lag in the last 5 minutes was greater than 1 second 
- to alerting when average replica lag in the last 10 minutes was greater than 2 seconds
The alert was firing too many false negatives where it immediately resolved.
=> Increase replica lag alert params.

modules/datadog_agent/main.tf, modules/datadog_agent/variables.tf, modules/metric_ingestor/datadog.tf
Metrics ingestor only runs a DD agent container and no other containers. One container must be essential in order for it to spin up
=> Make datadog agent essential for metrics ingestor

indexer/lambda.tf, indexer/locals.tf, indexer/rds.tf, indexer/variables.tf
=> [CT-578] Add aws secret for db password

indexer/locals.tf
`SEND_SUBACCOUNT_WEBSOCKET_MESSAGE_FOR_STATEFUL_ORDERS` being `false` for `vulcan` and `true` for `ender` leads to stateful orders not showing up on the orderbook.
=> Disable test flag.

modules/metric_ingestor/datadog.tf, modules/metric_ingestor/variables.tf, modules/validator/datadog.tf, modules/validator/variables.tf
This allows deployer to specify which metrics to exclude when forwarding to DD.
Some examples of metrics to exclude:
* `.*cometbft_p2p.*`
=> [TRA-241] Add `exclude_metrics` to validator and metrics ingestor

indexer/terraform.tfvars
Removing 1a from config since it is lagging on the indexer
=> Update availability Zones to remove 1a from mainnet indexer

indexer/terraform.tfvars
This reverts commit 7f8c7b9ccfd69f2305233e701c9ed28cfd287c25.
which remove 1a availability zone
=> Revert "Update availability Zones to remove 1a from mainnet indexer"

indexer/s3_bucket.tf, indexer/variables.tf
bucket and rds snapshot bucket
Default:
- enable lifecycle
- 7 days for fullnode snapshot, 31 days for logs and rds snapshot
=> Allow to enable lifecycle for snapshot bucket, load balancer logs

indexer/locals.tf, indexer/msk.tf
current kafka verion will become deprecated 
reduce session timeout to streamline new lead broker election
=> upgrade kafka version and reduce session timeout

indexer/rds.tf, indexer/route53.tf, indexer/variables.tf
Allow to enable/disable:
- multi_az on RDS master node
- read_replica_2 instance
With enable_rds_main_multiaz = true and create_read_replica_2 = true (default values that works for mainnet, testnet ), this requires changes in state due to index. No new resources are created or deleted.
=> Allow to enable/disable multi_az option on master node and remove read_replica_2 instance on dev*

indexer/ecs.tf
Indexer ecs services  tasks are placed in private  subnet. All the external connection with be routed throught NAT Gateway.
Therefore, set assign_public_ip = false to avoid wasted public ip and cost.
=> Set assign_public_ip = false as all the tasks are in private subnet

indexer/backup_full_node_ap_northeast_1.tf, indexer/ecs.tf, indexer/full_node_ap_northeast_1.tf, indexer/lambda.tf, indexer/snapshot_full_node_ap_northeast_1.tf, indexer/variables.tf, modules/validator/ecs.tf, modules/validator/variables.tf
New 3 variables:
- fullnode_ecs_task_cpu_architecture
- indexer_ecs_task_cpu_architecture
- lambda_cpu_architecture
Default value: X86_64 to be ready with existing docker images
=> Allow to changes ecs tasks architecture, lambda function.

indexer/backup_full_node_ap_northeast_1.tf, indexer/route_table.tf, indexer/security_group.tf, indexer/variables.tf, indexer/vpc.tf
New variable create_backup_full_node to allow disable backup_full_node
Default: true
Note that even with true, state needs to be changed as the index of `module.backup_full_node_ap_northeast_1` has become `module.backup_full_node_ap_northeast_1[0]`. And state migration happens automatically by moved block
=> Allow to disable backup_full_node

indexer/locals.tf
Needed for fetching AZ ID which is the rack id for kafka brokers.
=> Add AWS_REGION envvar to services that connect to kafka

indexer/locals.tf
Some of the previously adjusted values were invalid fargate configurations.
=> Adjust ECS memory and cpu

indexer/acm.tf, indexer/load_balancer.tf, indexer/security_group.tf, indexer/variables.tf
This load balancer is public facing, general best practice is to default to HTTPS since HTTP is not encrypted
=> Remove option to create load balancer without HTTPS option.

indexer/rds.tf
This is required for the postgres upgrade.
This is only for dev environments. All production environments are already on postgres 16.8+ and this is a no-op
=> Update parameter group to postgres16.

indexer/rds.tf
This can potentially cause an outage because we do set SSL to true in our indexer jobs
=> Set force_ssl default to false for RDS param groups
